---
title: "Welcome to this class!"
format: html
editor: visual
---

This website will walk you through the tutorials for the *Topics in Economics* (1S002) course of Ecole Polytechnique's Bachelor program.

The course has 3 main objectives:

1.  Know the basics of R

2.  Manipulate the standard statistical and empirical tools

3.  Write an original research output.

> **Practical information**
>
> **TA**: [Aurel Mélard](https://sites.google.com/view/aurel-melard)
>
> **Schedule**: Wednesday morning (check Synapses regularly for any changes in room).
>
> **Required software**: R and its IDE, RStudio (all free). You may download it [here](https://posit.co/download/rstudio-desktop/). Create a free account to use [Overleaf](https://www.overleaf.com). Bring you own laptop or use the lab's computer. The data used in the tutorials are on Moodle. You will also be able to download to find the solved exercices after each tutorial on Moodle.
>
> **Rules**: Send me an email if you miss the class. I trust you to follow thoroughly the class. Do not hesitate to work in small groups.

## Class outline

-   [**Tutorial 1**](https://aurel-melard.github.io/2026_eco1s002/tutorial1.html#/title-slide) **(11/02 - computer session)**
    -   Presentation of the class objectives
    -   First hands on R
    -   First hands on LaTeX
-   [**Tutorial 2**](https://aurel-melard.github.io/2026_eco1s002/tutorial2.html) **(18/02)**
    -   Baseline Solow model derivations
    -   Solow model extensions
-   [**Tutorial 3**](https://aurel-melard.github.io/2026_eco1s002/tutorial3.html) **(25/02 - computer session)**
    -   Replication of Mankiw et al. (1997)
    -   First hands on the OLS estimator
    -   Estimating the baseline and augmented Solow models
-   [**Tutorial 4**](https://aurel-melard.github.io/2026_eco1s002/tutorial4.html) **(11/03 - computer session)**
    -   OLS bias and Instrumental Variables
    -   Replication of Acemoglu et al. (2010)
    -   Export the results
-   **Tutorial 5 (18/03)**
    -   Discussion on the group project
    -   Q&A
-   [**Tutorial 6**](https://aurel-melard.github.io/2026_eco1s002/tutorial6.html) **(01/04 - computer session)**
    -   Autonomous replication of an IV paper (handed in)
-   **Tutorial 7 (08/04 - computer session)**
    -   Treatment effect
    -   Solution of Tutorial 6
-   [**Tutorial 8**](https://aurel-melard.github.io/2026_eco1s002/tutorial8.html) **(15/04)**
    -   Refresher on utility maximization program
    -   Intertemporal maximization problem
-   [**Tutorial 9**](https://aurel-melard.github.io/2026_eco1s002/tutorial9.html) **(22/04 - computer session)**
    -   Work-leisure trade-off
    -   Women labour force participation
-   [**Tutorial 10**](https://aurel-melard.github.io/2026_eco1s002/tutorial10.html) **(06/05 - computer session)**
    -   How to write the research project
-   [**Tutorial 11**](https://aurel-melard.github.io/2026_eco1s002/tutorial11.html) **(13/05 - computer session)**
    -   Difference-in-differences estimation
    -   Marriage output matrices
    -   Measures of assortative mating
-   **Tutorial 12 (20/05)**
    -   Mock exam correction
-   **Tutorial 13 (27/05)**
    -   Research project
    -   Final Q&A
-   **Tutorial 14 (TBD)**
    -   Restitution of the group projects *(graded)*

## About this site

This site is for teaching purpose. The majority of its material was built by [Matéo Moglia](https://mateomoglia.github.io/), who taught this class in previous years.

It is inspired by the following sources:

-   [Florian Oswald](https://floswald.github.io) teaching material at Sciences Po

-   [R Tutorials](https://mtes-mct.github.io/parcours-r/) of the French Ministry of Ecology (in French)

-   The infamous online book [Econometrics with R](https://www.econometrics-with-r.org)